CREATE TABLE app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) UNIQUE,
    password VARCHAR(200),
    role VARCHAR(20),
    name VARCHAR(100)
);

CREATE TABLE audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50),
    action VARCHAR(10),
    endpoint VARCHAR(200),
    timestamp TIMESTAMP
);

CREATE TABLE exchange_rate (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   currency_from VARCHAR(10),
   currency_to VARCHAR(10),
   rate DOUBLE
);

CREATE TABLE exchange_operation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_name VARCHAR(100),
    initial_amount DOUBLE,
    final_amount DOUBLE,
    exchange_rate DOUBLE,
    currency_from VARCHAR(10),
    currency_to VARCHAR(10),
    process_date TIMESTAMP
);
